package net.codes;

public enum EventCode {
    NONE,

    EMPTY_QUERY_RESULT,
    DISPLAY_HELP,
    EMPTY_COLLECTION,

    ELEMENT_NOT_FOUND,
    INVALID_AGE,
    NO_ELEMENTS_DELETED,
    NO_RIGHTS_TO_MODIFY,

    INCOMPATIBLE_TYPE,

    DATABASE_CONNECTION_NOT_ESTABLISHED,
    DATABASE_ERROR,

    LOGIN_ALREADY_EXISTS;
}
